### ISSUE TITLE
Doesn't find log files

### ISSUE THREAD

**Issue by wernllio** [Painter602/EDLogReader#11]
So i tried using the latest release and cant seem to figure out how to solve this issue.
![image](https://user-images.githubusercontent.com/100361777/167309657-f17194a2-2025-4883-b100-526d96830db4.png)

conf.json content:
{"Config": {"language": "en", "pathToLEDControl": "D:/Programme/VPC Software Suite/tools/VPC_LED_Control.exe", "pathToEDJournals": "%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/", "sleepTime": 5, "timeOut": 60, "timedeltaMs": 500, "resetTime": 10, "devices": {"RIGHT VPC Stick WarBRD": {"id": "3344 40CC"}, "LEFT VPC Throttle MT-50CM3": {"id": "3344 8194"}}}}
{"Event": "Default", "Interest": 1, "RIGHT VPC Stick WarBRD": {"Red": 0, "Green": 0, "Blue": 0, "cmd": 1 }, "LEFT VPC Throttle MT-50CM3": {"Red": 0, "Green": 0, "Blue": 0, "cmd": [ 5, 6, 7, 8, 9, 10 ]}}
{"Event": "HeatDamage", "Interest": 1, "LEFT VPC Throttle MT-50CM3": {"Red": 3, "Green": 1, "Blue": 0, "cmd": 10}}
{"Event": "HeatWarning", "Interest": 1, "LEFT VPC Throttle MT-50CM3": {"Red": 2, "Green": 1, "Blue": 0, "cmd": 10}}
{"Event": "HullDamage", "Interest": 1, "LEFT VPC Throttle MT-50CM3": {"Red": 3, "Green": 0, "Blue": 0, "cmd": 8}}
{"Event": "UnderAttack", "Interest": 1, "LEFT VPC Throttle MT-50CM3": {"Red": 3, "Green": 1, "Blue": 1, "cmd": 9}}
{"Event": "Cargo", "Interest": 0}
{"Event": "NavRoute", "Interest": 0}
{"Event": "Outfitting", "Interest": 0}
{"Event": "Shipyard", "Interest": 0}
{"Event": "FSDJump", "Interest": 1, "LEFT VPC Throttle MT-50CM3": {"Red": 3, "Green": 0, "Blue": 0, "cmd": 1}}

**Comment by Painter602** [comment]
Hello
I just jumped into Elite Dangerous, the first time in over a year.
It may be that, in your set-up the log files are written to a place.  You'll have to search for your log files, and amend the pathToEDJournals.

You are looking for a folder with file called:
- Journal.date-stamp.log, where date-stamp changes from file to file.

If you search for Journal, that should find the files.

HTH
Painter

p.s. OT: The format of the date-stamp has changed in the past year, but this doesn't affect the log reader.

**Comment by Painter602** [comment]
p.s. Searching for your 'Elite Dangerous' log folder might be quicker than searching for 'Journal', and should give fewer returns.

**Comment by wernllio** [comment]
The thing is, the folder do be the Journal folder 
![image](https://user-images.githubusercontent.com/100361777/167317478-abad921d-8853-44c8-825e-49c3a5584f6d.png)

**Comment by Painter602** [comment]
OK, we'll have to try making the log path explicit.

Try this - sorry for long, detailed post

- Go to the log reader's Config.json file.
- Right-click on the Config.json file.
- From the pop-up menu, click copy.
- In the same folder, but not hovering over any files, right-click and select paste
   this should create a copy, or back-up file.  You can use this if there are problems later.
- Open Config.json in Notepad or a similar text editor (***not*** Word, nor WordPad*).  Keep it open for now.
- Go to the Journal folder you found (above)
- Right click on one of the files
- Select properties
- On the General tab, there should be a field labelled Location.
- Use your mouse cursor to highlight all of the location value (typically starts with C:\ or D:\, and ends with Elite Dangerous)
- Click <CTRL>C to copy
- Go back to your open Config.json
- Highlight the **%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/** in the first line
- Press <CTRL>V to past your path.
- Make sure the text you've just pasted is a) complete, and b) surrounded by double quotes.
- Save the Config.json file

Try launching the log reader now.  It should now find the log files.

HTH
Painter

*Sorry if you know this, but other people may read this and need the information :)

**Comment by wernllio** [comment]
Already tried that, but for some reason it works now.
Im not sure if thats due to me typing it in and it fucked up something with keyboard inputs but it works with forward slashes (/) and ending with a forward slash (Elite Dangerous/ )

but thanks a lot.
