### ISSUE TITLE
Is there a way to edit the events so multiple LEDs on the same device can be changed on the same event? 

### ISSUE THREAD

**Issue by Painter602** [Painter602/EDLogReader#3]
Simple editing of device names and IDs is all it takes to get this working for a CM3-Alpha combination.

The command codes for the CM3 are 5-10, one for each B button LEDs.
 Is there a way to edit the events so multiple LEDs on the same device can be changed on the same event? Currently, I can only change the Alpha, and/or one CM3 LED per event. 
 
 Source: Fixitman on Virpi's website, https://forum.virpil.com/index.php?/topic/2326-vpc_led_control-new-small-tool-to-control-leds-on-your-vpc-device/&do=findComment&comment=25988

**Comment by Fixitman333** [comment]
I already coded conf.json for testing on my lunch break at work. I didn't get to see the update until I got home. The test should still be valid for figuring out the command codes. The VPC_LED_Control application only offers 45 options (0-44), so I tested 1-44 on the throttle. Only cmd 5-10 have any effect. They correspond to buttons B1-B6 in the same order (5=B1 to 10=B6).

I'm in the process of downloading the updated files now. I'll post my test results when I have time.

**Comment by Fixitman333** [comment]
I'm unable to test with the patch. Note that I'm still using Win7 Pro, so I installed the latest version of Python for my OS - v3.8.9. If I run the script without changing anything, it freezes with a yellow box in the window:

![Default](https://user-images.githubusercontent.com/37125998/113641827-60c2eb80-964c-11eb-8926-1de234e88f20.jpg)

I thought this was because the path to VPC_LED_Control.exe was wrong, so I edited the path. This gave the same result. I then edited the throttle's name and ID only on the Config line - same result. After that, I replaced all instances of "LEFT VPC Stick WarBRD" with the throttle name. Running the script then resulted in a command window opening for a split second, and then closing again. 

I've determined that changing the ID and all names except in the final used event (WingJoin) will result in the yellow-box freeze. If I then change the device name on that final used event, it results in a crash. I also tried fully editing the Config line, and only the WingJoin event, and it froze instead of crashing.

That's about as far as I can get with testing at this time. Let me know if there's anything else I can try.

**Comment by Painter602** [comment]
Ah, sorry, didn't think I'd changed that bit of code.

What happened:
The script checks that all devices in the config file are attached to the PC.  If a device isn't connected, it stops and gives (should give) a warning.

Today, I've made changes to **EdLogReader.py** and **shared.py** to give better information now.
If that happens again, you should see a message that looks like this:

![Device_check](https://user-images.githubusercontent.com/80922213/113689339-25fb9a80-96c2-11eb-9d92-4a135b1d45bd.jpg)

We don't want to run the script without the devices attached, or it will start spamming VPC_LED_Control windows on your screen.

**Comment by Fixitman333** [comment]
I did a quick test of this before work. Now the reason for the yellow box "freeze" is obvious. I'm still getting a crash when running the script with a fully edited conf.json.. I created a short video of it this morning, but ran out of time. I'll examine it after work to see what's displayed briefly.

**Comment by Painter602** [comment]
Ok,
~~I'm not sure if you had a chance to download the changed files earlier.~~
I've added further changes to EdLogReader.py and shared.py, so they should produce a log file (EdLogReader.log) when a missing device is identified.

If you can re-download **EdLogReader.py** and **shared.py**, we should be able to chase down the problem.

**Comment by Fixitman333** [comment]
I updated the files and ran the script with a fully edited conf.json file. It still crashes before "EdLogReader - Startup" opens. No log file was produced. All I get is a brief command window. I was able to record it with OBS, then get a screenshot from a video editor. The quality is poor, but at least it's readable:
![Crash_002](https://user-images.githubusercontent.com/37125998/113787272-b52ba100-9708-11eb-8410-17c67735e537.jpg)

Edit: This is a cleaner image from this morning, before today's changes:
![Crash_001](https://user-images.githubusercontent.com/37125998/113787583-49960380-9709-11eb-9d33-254b49c069ed.jpg)

**Comment by Fixitman333** [comment]
I discovered that line has something to do with journal files. I changed "fPath" to the complete path to my journal files to see what would happen. I now get a command window titled "C:\Windows\py.exe". It only has a flashing cursor, and won't accept any keyboard input. All I can do is drag it around, or close it.

**Comment by Painter602** [comment]
Thanks, your screen-shot helps.
You are correct,  it is a problem with fPath.  If it is still open, you may as well close that window.

You've worked the next bit out, but, if anybody else sees this, they mayl want to know.

Take a look at the Config line in conf.json.
The default is "fPath":"%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/"

fPath is the key, and mustn't change*, but the %HOMEPATH% stuff might.

The default values of this are: C:\Users\\*user_name*\Saved Games\Frontier Developments\Elite Dangerous, but your system is set up differently (substitute your login name for *user_name*).

I'll make a change to try and catch that problem (somebody else will, doubtless do something similar)

.
.

\* I'll think about replacing fPath with something more meaningful; see if I can find a way without breaking your version of the script.

**Comment by Fixitman333** [comment]
My system is using that default location. Is there a difference between these?:

"fPath":"%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/"

"fPath":"C:/Users/_myusername_/Saved Games/Frontier Developments/Elite Dangerous/"

The first results in the crash, the second produces a non-interact-able command window.

**Comment by Painter602** [comment]
p.s.
If you have similar problems running the scripts in future ...

Try browsing to your EDLogReader folder in windows, and right click on EDLogReader.py.  You should then be able to 'edit' the file with IDLE.

When the file is open in IDLE, Select **_Run_** -> **_Run Module_** to run the script  That will open up another window which *should* be more friendly than the black screen (command screen).

**Comment by Painter602** [comment]
> My system is using that default location. Is there a difference between these?:
> 
> "fPath":"%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/"
> 
> "fPath":"C:/Users/*myusername*/Saved Games/Frontier Developments/Elite Dangerous/"

It depends on how %HOMEPATH% is set up; there may be a difference.
  
If you browse to your ??/Saved Games/Frontier Developments/Elite Dangerous/ folder, you should be able to see a lot of files that look like Journal.210399999999.01.log  where 9999 is a string of numbers.

Right click on any of these files and select Properties.  Look for Location and high-light the location shown.
Use <Ctrl-C> to copy the path, and paste that into fPath in your config.json file.

You may have to drag the high-light around a bit, because the properties window is too narrow for the file path.

**Comment by Fixitman333** [comment]
Both locations are the same on my system. I was wondering if the code somehow treated each differently. Running either in IDLE Shell results in the same error message as before.

I just discovered the command line parameters. I'll use the /d to test the multi-LED code tomorrow afternoon.

**Comment by Painter602** [comment]
A big change to the way ED Log Reader's window works - a big change from my perspective.

The window will now remain open while the script is running.

If there is little activity in the log file (and, by implication in Elite Dangerous), the Reader will report on its activity (scanning the log file).

If the game is active, that should be reflected in the Virpil devices' LEDs.
The reader's window will remain quiet.

Yet again, the changed files are **EdLogReader.py** and **shared.py**.

**Comment by Painter602** [comment]
> My system is using that default location. Is there a difference between these?:
> "fPath":"%HOMEPATH%/Saved Games/Frontier Developments/Elite Dangerous/"
> "fPath":"C:/Users/myusername/Saved Games/Frontier Developments/Elite Dangerous/"
>The first results in the crash, the second produces a non-interact-able command window.

The %HOMEPATH% version should be identical with the C:/Users version.
Use the one that works (the second version).

The non-interact-able command window is (should be) a python shell.  Closing this will stop the script.
Some program generated text can appear there, but the window closes when Python stops.

I hope the changes scripts will give you a more friendly window as well as the shell.
You can minimize or ignore the command window  - the normal, interactive window should give you better information now.

**Don't** close the black command window unless you want to stop the script.

**Comment by Fixitman333** [comment]
It appears to be working without errors now, provided I use the "C:/Users/..." option for fPath. The only issue I see is when I click exit. Win7 opens a window stating "Python has stopped working".  The Win7 provided details show that it crashed, and the python shell window has a single line in it:

Tcl_AsyncDelete: async handler deleted by the wrong thread

This only happens when running in the python shell (double-click EdLogReader.py, or a shortcut). Running it in the IDLE shell closes properly. Also-The exit button doesn't change state when clicked, and it takes a second or two to actually close (not a big deal at this time).

I'm going to get started on creating a custom conf.json file for testing multi-LED control. Once I've verified that's working, I'll move on to in-game testing.

**Comment by Fixitman333** [comment]
All LED's are changing colors colors as expected, both with the /d parameter, and in-game. Looking good so far.

How does "Interest" affect things? I don't understand what "_influences colour range_" means.

**Comment by Painter602** [comment]
Events with Interest 0 (zero) are ignored at run-time.
Interest 1 (one) and above generate an LED colour change

Higher levels are legacy from earlier versions of the script, they are treated as 1 now.

**Comment by Painter602** [comment]
Thank-you for your efforts so far with this @Fixitman333 
The program is better for your feed-back.

The Tcl_AsyncDelete happens because of the way the script is written - I plan to look into that later, but it isn't a top-priority.

I agree exiting is slow, again, not a top priority.

p.s. I need to change the text "influences colour range", that is redundant now.

**Comment by Painter602** [comment]
I've now merged branch 2 with the main branch, deleting the old branch 2.
 (I also deleted branch1)

**Comment by Painter602** [comment]
I made some major changes today:
>Revised calls to the main window so that the script is more responsive.
>Moved most buttons into menu options, removing the buttons.
>Removed 'Skip Device Testing' button, replacing it with a run-time test.
>
>Removed most command line options.
>Started preparations for multi-language support.
>
>Extended the range of commands in the English language translations file.

The changed files are in the main branch:
- EdLogReader.py
- shared.py 
- lang.en.json

@Fixitman333 
I'd like to put a Thank-you section in the About window, and say thank you for helping.
Would that be OK with you?

**Comment by Fixitman333** [comment]
> Events with Interest 0 (zero) are ignored at run-time.
> Interest 1 (one) and above generate an LED colour change
> 
> Higher levels are legacy from earlier versions of the script, they are treated as 1 now.

I'm thinking "Interest" could be very useful in changing something like the time delay before switching back to default. It seems like the code waits for a minute without any "Interest: >0" events, then switches the LEDs back to the colors set in the default event. A 2 or 3 could temporarily change that delay to 1/2 or 1/4 of the normal delay time, A 4 could just turn off the delay until the next event. This wouldn't do much with two Alpha's, but it could be very useful with multiple-LED devices.

I don't know if such a thing is simple to add, or a massive undertaking. I'm just sharing an idea, with no expectations. 

> I made some major changes today:
> 
> > Revised calls to the main window so that the script is more responsive.
> > Moved most buttons into menu options, removing the buttons.
> > Removed 'Skip Device Testing' button, replacing it with a run-time test.
> > Removed most command line options.
> > Started preparations for multi-language support.
> > Extended the range of commands in the English language translations file.
> 
> The changed files are in the main branch:
> 
> * EdLogReader.py
> * shared.py
> * lang.en.json
> 

I'll download the updates after posting this. I may not be able to try it until the weekend, but I will let you know if there are any issues.

> @Fixitman333
> I'd like to put a Thank-you section in the About window, and say thank you for helping.
> Would that be OK with you?

That's totally up to you, but it was never an expectation. If you do add it, refer to me as Fixitman. I'm only Fixitman333 here because someone had already claimed Fixitman.

**Comment by Painter602** [comment]
Yet more changes have been uploaded this evening - including a new file.
A thank-you appears in the About box (Help -> About)

> I'm thinking "Interest" could be very useful in changing something like the time delay before switching back to default. It seems like the code waits for a minute without any "Interest: >0" events, then switches the LEDs back to the colors set in the default event. A 2 or 3 could temporarily change that delay to 1/2 or 1/4 of the normal delay time, A 4 could just turn off the delay until the next event. This wouldn't do much with two Alpha's, but it could be very useful with multiple-LED devices.
>
> I don't know if such a thing is simple to add, or a massive undertaking. I'm just sharing an idea, with no expectations.

Mmm.  Think that is a fresh issue, or feature request.
It is do-able, and I like the idea of using interest as a multiplier to hold the state of an LED.  There may be an issue with prioritization there too - LED is in a long hold state, but another, 'more significant' event occurs to over-ride...

Before that, I want to write a configuration tool, to save hacking about in *conf.json* ... and to save me trying to find all the events in Odyssey manually. (I don't enjoy FPS games).

**Comment by Fixitman333** [comment]
I just downloaded the latest code for testing. IDLE Shell shows errors, and the EDLogReader window is blank. 

I believe the multi-LED issue is officially resolved. Should I continue to post issues here, or open a new issue?Also: a version system would be very helpful. Referring to the date and time of my last download isn't very intuitive.

I'll post the error output from IDLE once I know where I should do so.

**Comment by Painter602** [comment]
>I believe the multi-LED issue is officially resolved. Should I continue to post issues here, or open a new issue?

Thanks, it is good to know the multi-LED issue has been resolved.
Especially, thank-you with your help there, it isn't something I could test myself.

Post your current errors here, but we can open a new issue for other features and problems.
There is nothing to stop you opening new issues now (for example, the request to change the way *Interest* works).

> Also: a version system would be very helpful. Referring to the date and time of my last download isn't very intuitive.

I have a versioning system that *should* appear in my next upload. I won't say too much about it yet, 'cause it may change before then.

> I'll post the error output from IDLE once I know where I should do so.

You may as well post the errors here.

**Comment by Fixitman333** [comment]
The entire output from the IDLE Shell is: 

>================== RESTART: J:\EDLogReader-main\EdLogReader.py =================
>Traceback (most recent call last):
>  File "J:\EDLogReader-main\EdLogReader.py", line 959, in <module>
>    main()
>  File "J:\EDLogReader-main\EdLogReader.py", line 954, in main
>    Window()
>  File "J:\EDLogReader-main\EdLogReader.py", line 101, in __init__
>    self.menu()
>  File "J:\EDLogReader-main\EdLogReader.py", line 233, in menu
>    if not file_check( file_filter ):
>  File "J:\EDLogReader-main\EdLogReader.py", line 601, in file_check
>    f"{config.config['__fPath__']}"
>KeyError: '__fPath__'

I tried it with and without the game running: same result. I also tried with /d, but it looks like it's been removed.

**Comment by Painter602** [comment]
Thanks.
The cause of that error was obscure, but I think I've solved it.

A few changes - the important one is that, from the About Box, you can now copy the program name and version to your clip board, and paste from there.
Hover over the name at the bottom right-hand side, and click to copy.

(The about box also has a clickable link to these issues pages)


The /d option has been replaced with the Device Test button.

I'm not sure how useful the Device Test is now.  The Use Old Files button is much more responsive, and gives a more realistic test (if dull when re-running a combat/res zone .... so many 'ShipTargeted' events)

**Comment by Painter602** [comment]
p.s. the revised code is in the main branch.

**Comment by Painter602** [comment]
pps. Current version is EdLogReader v0.04.12:0.04.11

**Comment by Fixitman333** [comment]
I can't use the compiled version because it isn't compatible with Win 7. I'll continue testing via source as I have time.

**Comment by Painter602** [comment]
Thanks for letting me know, I'll see I can find a way around that.
Which version of Python are you using?  3.8.x or 3.7.x

**Comment by Fixitman333** [comment]
I'm using version 3.8.9.

**Comment by Painter602** [comment]
Thanks for letting me know your python version - at least their code runs on your PC.

I've produced a 32 bit binary (here: https://github.com/Painter602/EDLogReader/releases/tag/v0.1.0-alpha ) together with another 64 bit version.
The 32 bit was compiled with Python 3.8.9, the 64 bit with 3.9.4.

It'll be interesting to know if it works on your PC.  
There is one file that the installer tries to publish, but that I don't know that I can share ... MicroSoft's VCRUNTIME140.dll
That should be on your PC anyway - it is part of MS's Visual C++ distribution.
 (And, presumably, supplied with Python)

**Comment by Fixitman333** [comment]
The 32-bit version works properly on my PC (Win 7 Pro 64-bit).

**Comment by Painter602** [comment]
Thanks, that is good to know.
Think that next time *both* versions will be Python 3.8.x

Thank-you again for your help @Fixitman333 , this log reader looks *much* better now, and that is because of your interest.

The Interest idea is in a new issue (link: https://github.com/Painter602/EDLogReader/issues/9 ).
I'll close this issue now.  Feel free to create new ones
